#!/bin/bash
# PythonAnywhereへのデプロイ用ファイル一覧

echo "=== PythonAnywhereにアップロードするファイル ==="
echo ""
echo "以下のファイル/フォルダをアップロードしてください："
echo ""
echo "web/"
echo "  ├── app.py"
echo "  ├── wsgi.py"
echo "  ├── templates/"
echo "  │   ├── index.html"
echo "  │   └── recommend.html"
echo "  └── static/"
echo "      └── style.css"
echo ""
echo "analysis/"
echo "  └── recommender.py"
echo ""
echo "config/"
echo "  └── rankings.py"
echo ""
echo "data/"
echo "  └── daily/"
echo "      └── daily_sbj_*.json"
echo ""
